---
kind: pipeline
name: "viBroad-Service Pull Request"

steps:
  - name: test-pull-request
    image: gradle:jdk11
    volumes:
      - name: cache
        path: /cache
      - name: docker
        path: /var/run/docker.sock
    commands:
      - export GRADLE_USER_HOME=/cache/.gradle
      - gradle build jacocoTestReport
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - build/reports/jacoco/test/jacocoTestReport.xml

trigger:
  event:
    - pull_request
  branch:
    - master

volumes:
  - name: cache
    host:
      path: /var/lib/cache/gradle
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: "viBroad Service"

steps:
  - name: build-master
    image: gradle:jdk11
    volumes:
      - name: cache
        path: /cache
      - name: docker
        path: /var/run/docker.sock
    commands:
      - export GRADLE_USER_HOME=/cache/.gradle
      - gradle build jacocoTestReport
      - echo -n "latest" > .tags
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - build/reports/jacoco/test/jacocoTestReport.xml

  - name: "build docker image"
    image: plugins/docker
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      auto_tag: true
      repo: docker.pkg.github.com/si87/public/vibroad-service
      registry: docker.pkg.github.com

  - name: deploy
    image: si87/drone-docker-service:0.1.0
    pull: always
    settings:
      api_endpoint: dockerapi.ttran.de
      api_version: v1.39
      api_password:
        from_secret: api_password
      api_user:
        from_secret: api_user
      registry_user:
        from_secret: registry_username
      registry_password:
        from_secret: registry_password
      registry_endpoint: docker.pkg.github.com
      service_name: vibroad-service
      service_docker_image: docker.pkg.github.com/si87/public/vibroad-service


trigger:
  event:
    - push
  branch:
    - master

volumes:
  - name: cache
    host:
      path: /var/lib/cache/gradle
  - name: docker
    host:
      path: /var/run/docker.sock

